apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-demo-app-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: gabriel8819
          repo: argocd-demo
  template:
    metadata:
      name: argocd-app-1
    spec:
      project: argo-demo
      source:
        repoURL: git@github.com:Gabriel8819/argocd-demo-ops.git 
        targetRevision: HEAD
        path: dev  
      destination:
        server: https://kubernetes.default.svc
        namespace: default
