apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        github:
          owner: gabriel8819
          repo: argocd-demo
      requeueAfterSeconds: 10
  template:
    metadata:
      name: argocd-app-1
    spec:
      project: argo-demo
      source:
        repoURL: https://github.com/Gabriel8819/argocd-demo-ops.git 
        targetRevision: HEAD
        path: dev  
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}
